<a href="https://colab.research.google.com/github/WildanMaulanaYahya/Datamining/blob/main/Modul1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NAMA : WILDAN MAULANA YAHYA
# NIM : 202410102079
# KELAS : DATMIN A

In [ ]:
#kode 1f
import numpy as np
arr = np.array([[4,4,5],[7,6,4],[9,7,4],[6,3,7]])
print(arr)

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]


In [ ]:
#kode 1g
import numpy as np
arr = np.array([[[7,8,5],[4,7,7],[7,1,9],[5,4,10]],[[2,1,2],[9,8,5],[3,7,3],[4,9,9]],[[2,9,3],[2,4,8],[1,6,6],[8,1,3]]])
print(arr)

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]


In [ ]:
#kode 2d
import numpy as np
arr = np.array([[1,8,8,2],[8,2,1,2],[10,1,4,7],[1,4,7,8],[8,2,3,4]])
arr[1::2] += 1
print(arr)
arr[:,0::2] += 2
print(arr)

[[ 1  8  8  2]
 [ 9  3  2  3]
 [10  1  4  7]
 [ 2  5  8  9]
 [ 8  2  3  4]]
[[ 3  8 10  2]
 [11  3  4  3]
 [12  1  6  7]
 [ 4  5 10  9]
 [10  2  5  4]]


In [ ]:
#kode 2e
import numpy as np
arr=np.array([[[7,8,5], [4,7,7], [7,1,9], [5,4,10]], [[2,1,2], [9,8,5], [3,7,3], [4,9,9]], [[2,9,3], [2,4,8], [1,6,6], [8,1,3]]])
print (arr[::-1])

[[[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]]


In [ ]:
#kode 2f
import numpy as np
arr=np.array([[[7,8,5], [4,7,7], [7,1,9], [5,4,10]], [[2,1,2], [9,8,5], [3,7,3], [4,9,9]], [[2,9,3], [2,4,8], [1,6,6], [8,1,3]]])
arr=arr.reshape (6,6)
print(arr)

[[ 7  8  5  4  7  7]
 [ 7  1  9  5  4 10]
 [ 2  1  2  9  8  5]
 [ 3  7  3  4  9  9]
 [ 2  9  3  2  4  8]
 [ 1  6  6  8  1  3]]


In [ ]:
#kode 3e
import numpy as np
arr = np.array([[5,10,10,7],[7,8,4,10],[9,10,2,5],[1,8,9,3],[6,10,5,2],[4,6,9,4]])

arr_1 = arr[:3,:2] #bagian kiri atas yang berisi 5,10,7,8,9,10
arr_2 = arr[3:,:2] #bagian kiri bawah yang berisi 1,8,6,10,4,6
arr_3 = arr[:3,2:] #bagian kanan atas yang berisi 10,7,4,10,2,5
arr_4 = arr[3:,2:] #bagian kanan bawah yang berisi 9,3,5,2,9,4

k1 = np.concatenate ((arr_4,arr_2),axis=1) #atas
k2 = np.concatenate ((arr_3,arr_1),axis=1) #bawah
arr_total = np.concatenate ((k1,k2),axis=0)
print(arr_total)


[[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]
